description: ChestXray Dataset

target:
  service: philly
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "msrlabs".
  vc: resrchvc 
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: rr1

environment:
  image: pytorch/pytorch:1.5-cuda10.1-cudnn7-devel
  setup:
    - pip install --user -r requirements.txt
    
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR

data:
    local_dir: $CONFIG_DIR/data/datasets/
    remote_dir: data/datasets/
 

# list of jobs to run, we run 2 jobs in this example
jobs:
  # name must be unique across the jobs
# - name: erm_oracle
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains kaggle_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1


- name: erm
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1
  
- name: rand_match
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --model_name densenet121 --n_runs 3 --os_env 1
  
- name: csd
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name csd --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --rep_dim 1024 --os_env 1
   
- name: irm
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name irm --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --penalty_s 5 --model_name densenet121 --n_runs 3 --os_env 1

- name: irm-50
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name irm --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 50.0 --penalty_s 5 --model_name densenet121 --n_runs 3 --os_env 1

- name: irm-100
  # one gpu
  sku: G1
  command:
  - echo "--debug" && python train.py --dataset chestxray --method_name irm --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 100.0 --penalty_s 5 --model_name densenet121 --n_runs 3 --os_env 1

# - name: perf_match
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name hybrid --match_case 0.01 --train_domains nih_trans chex_trans  --test_domains kaggle_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --penalty_aug 10.0 --os_env 1


# - name: erm_oracle_nih
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains nih_trans  --test_domains nih_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1

# - name: erm_nih
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains chex_trans kaggle_trans  --test_domains nih_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1
  
# - name: rand_match_nih
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains chex_trans kaggle_trans  --test_domains nih_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --model_name densenet121 --n_runs 3 --os_env 1
  
# - name: csd_nih
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name csd --match_case 0.01 --train_domains chex_trans kaggle_trans  --test_domains nih_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --rep_dim 1024 --os_env 1
   
# - name: irm_nih
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name irm --match_case 0.01 --train_domains chex_trans kaggle_trans  --test_domains nih_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --penalty_s 5 --model_name densenet121 --n_runs 3 --os_env 1
  
 
# - name: erm_oracle_chex
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains chex_trans  --test_domains chex_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1

# - name: erm_chex
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains nih_trans kaggle_trans  --test_domains chex_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --os_env 1
  
# - name: rand_match_chex
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name erm_match --match_case 0.01 --train_domains nih_trans kaggle_trans  --test_domains chex_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --model_name densenet121 --n_runs 3 --os_env 1
  
# - name: csd_chex
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name csd --match_case 0.01 --train_domains nih_trans kaggle_trans  --test_domains chex_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 0.0 --model_name densenet121 --n_runs 3 --rep_dim 1024 --os_env 1
   
# - name: irm_chex
#   # one gpu
#   sku: G1
#   command:
#   - echo "--debug" && python train.py --dataset chestxray --method_name irm --match_case 0.01 --train_domains nih_trans kaggle_trans  --test_domains chex_trans  --out_classes 2 --perfect_match 0 --img_c 3 --pre_trained 1 --epochs 40  --lr 0.001 --batch_size 16 --penalty_ws 10.0 --penalty_s 5 --model_name densenet121 --n_runs 3 --os_env 1


